plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
	id 'org.sonarqube'
}

group = 'com.contentgrid.liaison'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation ('com.contentgrid.common:contentgrid-common-spring-boot-starter:0.1.4') {
		capabilities {
			requireFeature('spring-boot-3')
		}
	}
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.fabric8:kubernetes-client:7.7.0'

	runtimeOnly ('io.micrometer:micrometer-registry-prometheus'){
		because "Trigger prometheus registry autoconfiguration & activate prom metrics endpoint. ACC-2942"
	}

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'

	testImplementation platform('org.testcontainers:testcontainers-bom:1.21.4')
	testImplementation "org.testcontainers:testcontainers"
	testImplementation "org.testcontainers:junit-jupiter"
	testImplementation "org.testcontainers:k3s"
	testImplementation 'org.awaitility:awaitility'
	testImplementation group: 'org.graalvm.js', name: 'js', version: '25.0.3'
	testImplementation group: 'org.graalvm.js', name: 'js-scriptengine', version: '25.0.3'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootBuildImage {
	def repository = "ghcr.io/xenit-eu/contentgrid-liaison"
	imageName = "${repository}:${project.version}"
	tags = "${project.version}".endsWith('SNAPSHOT') ? [ "${repository}:SNAPSHOT" ] : null

	docker {
		publishRegistry {
			url = project.findProperty('DOCKER_PUBLISH_REGISTRY_URL')
			username = project.findProperty('DOCKER_PUBLISH_REGISTRY_USERNAME')
			password = project.findProperty('DOCKER_PUBLISH_REGISTRY_PASSWORD')
		}
	}
}

bootRun {
	args = ["--spring.profiles.active=bootRun"]
}

jacocoTestReport {
	reports {
		xml.required = true
	}
}

sonarqube {
	properties {
		property "sonar.projectKey", "contentgrid-liaison"
		property "sonar.organization", "xenit-eu"
		property "sonar.host.url", "https://sonarcloud.io"
	}
}